Entero horas
Real Pbruto,ihss,tp
Cadena [25] nombre
Inicio
    Escriba "Ingresar el nombre: "
    Lea nombre
    Escriba "Ingresar las horas trabajadas: "
    Lea horas
    Pbruto <- horas * 50
    Si pbruto > 2400 entonces
        Ihss <- 84
    Fin si
    Tp <- (pbruto - ihss)
    Escriba "pago bruto    ", pbruto
    Llamar nueva_linea
    Escriba "Seguro social ", ihss
    Llamar nueva_linea
    Escriba "Total a pagar   ", tp
    Llamar nueva_linea
Fin