entero num1,num2,num3,mayor
inicio
    escriba "ingrese numero1: "
    lea num1
    escriba "ingrese numero2: "
    lea num2
    escriba "ingrese numero3: "
    lea num3
    si num1 > num2 entonces
       si num1 > num3 entonces
       mayor <- num1
       sino
     mayor <- num3
     fin si
    sino
    si num2 > num3 entonces
    mayor <- num2
    sino 
    mayor <- num3
    fin si
    fin si
    escriba "el mayor es: ", mayor
fin