real nota1,nota2,nota3,promedio
inicio
    escriba "ingrese primer nota: "
    lea nota1
    escriba "ingrese segunda nota: "
    lea nota2
    escriba "ingrese tercera nota: "
    lea nota3
    promedio <- (nota1 + nota2 + nota3)/3
    si (promedio >= 3.5) entonces
    escriba "su promedio es: ", promedio, " usted aprobo"
      sino
    escriba "su promedio es: ", promedio, "usted reprobo"
   fin si
fin